name: Build Flutter APK

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle' # Esto acelera las compilaciones

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Build APK
        run: |
          # Entramos a la carpeta del proyecto
          cd $(find . -name pubspec.yaml -exec dirname {} \;)
          
          flutter pub get
          
          # IMPORTANTE: Forzamos a Gradle a usar menos memoria para evitar que el runner mate el proceso
          # También quitamos el --debug para que use la firma release (aunque sea la de defecto de GH)
          flutter build apk --release --no-tree-shake-icons --dart-define=GRADLE_OPTS="-Xmx4g -XX:MaxMetaspaceSize=512m"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: "**/build/app/outputs/flutter-apk/app-release.apk"